### ISSUE TITLE
Carbon method signature update caused breaking error

### ISSUE THREAD

**Issue by jsiebach** [jenssegers/agent#112]
Updating Carbon to 1.23 caused a breaking change:

Declaration of Jenssegers\Date\Date::diffForHumans(?Carbon\Carbon $since = NULL, $absolute = false, $short = false) should be compatible with Carbon\Carbon::diffForHumans(?Carbon\Carbon $other = NULL, $absolute = false, $short = false, $parts = 1)

**Comment by danieltamas** [comment]
Yeah, I can confirm this on my end as well.

**Comment by f4llou7** [comment]
and
Declaration of Jenssegers\Date\Date::setTranslator($translator) should be compatible with Carbon\Carbon::setTranslator(Symfony\Component\Translation\TranslatorInterface $translator)
