### ISSUE TITLE
Problem when installing in laravel 5.6

### ISSUE THREAD

**Issue by widimiras** [jenssegers/agent#123]
Problem 1
    - The requested package symfony/psr-http-message-bridge (locked at v1.0.2, required as 0.2) is satisfiable by symfony/psr-http-message-bridge[v1.0.2] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for symfony/psr-http-message-bridge 0.2 -> satisfiable by symfony/psr-http-message-bridge[v0.2].
    - Conclusion: remove symfony/http-foundation v4.0.9
    - Conclusion: don't install symfony/http-foundation v4.0.9

**Comment by jenssegers** [comment]
As far as I know `symfony/psr-http-message-bridge` is not used in this library.
