### ISSUE TITLE
Pixel 2 XL recognized as an HTC

### ISSUE THREAD

**Issue by acidjazz** [jenssegers/agent#131]
I know the hardware is HTC, but I don't think we want `$agent->$device()` reporting that.

Agent:
`Mozilla/5.0 (Linux; Android 9; Pixel 2 XL Build/PPR1.180610.009) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36`

**Comment by jenssegers** [comment]
For mobile devices, agent uses https://github.com/serbanghita/Mobile-Detect. It would be best to create the issue over there and it will be automatically be included in agent 👌
