### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by khan-ewbcore** [jenssegers/agent#152]
Is it supported laravel 6 ?

**Comment by roldandvg** [comment]
This package is ready for migration to Laravel 6 or is maintenance unattended ?, thanks

**Comment by tiagosimoesdev** [comment]
I have used in local and doesn't seem to break anything .. but it would be great if there was a confirmation from the author

**Comment by jenssegers** [comment]
There is no explicit dependency on Laravel so you should be good to go!
