### ISSUE TITLE
Chromium based Edge not detected

### ISSUE THREAD

**Issue by beko1997** [jenssegers/agent#160]
The new version of Edge is based on Chromium and is set to be launched on the 15th of January 2020 (https://www.microsoftedgeinsider.com/whats-new). The user agent is currently detecting Edge as Chrome. 

Example of user agent form edge: ``Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.29 Safari/537.36 Edg/79.0.309.18``

**Comment by strausmann** [comment]
The Defection for Edge Chromium does not working. The User Agent from my Edge Chromium is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71` but he says it is Chrome.
