### ISSUE TITLE
php-console-color, php-console-highlighter are abandoned

### ISSUE THREAD

**Issue by nitzanb** [jenssegers/agent#167]
I've Installed the agent package using composer, got 2 notices while installing:

- Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
- Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.

They were marked as abandoned fairly recently and I don't see any issues with that for now, but it might be a good idea to switch these packages in the future.

**Comment by jenssegers** [comment]
Thanks for notifying!

**Comment by jenssegers** [comment]
I'm not getting these warnings. Might be part of an older version of phpunit or something.
