### ISSUE TITLE
Error in configuration - Class 'Jessengers\Agent\AgentServiceProvider' not found

### ISSUE THREAD

**Issue by mssct-1999** [jenssegers/agent#169]
Hello,

When i used your package i got an error : Class 'Jessengers\Agent\AgentServiceProvider' not found. But when i check the jessengers directory in the vendor, i have this class, but it seems that it doesn't find it... 

Do you got a solution for this problem ? 
(I'm using Laravel 5.8 / Composer 1.8.6)

Thanks.

**Comment by jenssegers** [comment]
There's a typo in your import.
