### ISSUE TITLE
Call To Undefinde Method

### ISSUE THREAD

**Issue by inov** [jenssegers/agent#20]
For every method I try to use with the Facade class I get the following error:

Call to undefined method Jenssegers\Agent\Facades\Agent::isMobile() (or similar )

Can anyone tell me how to solve this? I did include the Facade and the ServiceProvider in my app/config/app.php

**Comment by mulhollandgroup** [comment]
I am also experiencing this same issue.  My composer has been freshly updated and I'm able to successfully initialize the class, but get the same failure when I try to use any of the methods.  Was there some sort of resolve for this?

**Comment by velkymx** [comment]
Yes, with Laravel 5 and Jenssegers installed you get this error:

```
FatalErrorException in PostsController.php line 32:

Call to undefined method Jenssegers\Agent\Facades\Agent::platform()
```
Request code:
```
        $agent = new \Agent;

        return $agent->platform();
```

**Comment by velkymx** [comment]
If I call it statically it returns false.

```
return \Agent::browser($request->header('user-agent'));
```

**Comment by luchorengo** [comment]
Just use `use Jenssegers\Agent\Agent;` instead of `use Agent;` and it works fine.

**Comment by sleenen** [comment]
Then why have the serviceprovider and facade ?!
