### ISSUE TITLE
Consider more extensive robot detection

### ISSUE THREAD

**Issue by phirschybar** [jenssegers/agent#24]
Great library. We're using it in production. Have you considered extending the list of robots to include more possibilities? I would think any user agent string with the term 'bot' in it would do the trick.

**Comment by xitude** [comment]
+1

**Comment by tlorentzen** [comment]
Maybe a config file so people can extend the list of robots.

**Comment by jenssegers** [comment]
There's a PR with more bots #28, I'll take a look into it.
