### ISSUE TITLE
Microsoft Edge not support

### ISSUE THREAD

**Issue by BePsvPT** [jenssegers/agent#38]
Will Microsoft Edge browser support be added soon?

**Comment by jenssegers** [comment]
What is Edge's user agent?

**Comment by BePsvPT** [comment]
Microsoft Edge:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.<OS build number>

Windows 10 Mobile:
Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; DEVICE INFO) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Mobile Safari/537.36 Edge/12.<OS build number>

Source: https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx
