### ISSUE TITLE
Same problem: isMobile does not exists

### ISSUE THREAD

**Issue by ppalmeida** [jenssegers/agent#39]
Hi.

I was trying to use your lib, but the method isMobile() was not available (the very same problem than this link: https://github.com/jenssegers/agent/issues/20).

So, I used MobileDetect directly. I do not know what I did wrong, but MobileDirect worked fine.

Thank you.

**Comment by jenssegers** [comment]
Agent directly extends the original MobileDetect class, so it should be available on both.

**Comment by jenssegers** [comment]
What is the error message that you are getting?

**Comment by Ka0o0** [comment]
If it's the same as the guy in issue #20 had, double check that you set the Facade and the ServiceProvider in your app.php correctly (assuming you get this error in Laravel)

You also have to pay attention to the namespace you use:

Jenssegers\Agent\Facades\Agent is just the Facade class -> Jenssegers\Agent\Agent is the class to use, which does inherit from Mobile_Detect

**Comment by danieltrolezi** [comment]
For the Agent facade to work and inherit the Mobile_Detect methods, you need to add in you config/app.php this: 

> 'Agent' => Jenssegers\Agent\Agent::class

and not this (as discribed in the docs):

`Agent' => 'Jenssegers\Agent\Facades\Agent',`

If you add the Jenssegers\Agent\Facades\Agent, the Agent class don't inherit the Mobile_Detect methods.
