### ISSUE TITLE
isTablet not working correctly

### ISSUE THREAD

**Issue by colevr** [jenssegers/agent#48]
Hi, 

i setup this configuration

```
use Jenssegers\Agent\Agent;

$agent = new Agent();

if($agent->isMobile()){
    $realpath = "resources/mobile";
}
else{
    $realpath = "resources/desktop";
}
```

however, when i visit the application from an IPAD, i see the mobile version.

Thanks!

**Comment by jenssegers** [comment]
iPad is also mobile. Check `$agent->isTablet()` first.

**Comment by colevr** [comment]
thanks! i solved using this:
if ($agent->isMobile() && !$agent->isTablet()) {

sorry, and thanks!
