### ISSUE TITLE
Implement isIphone, isIpad?

### ISSUE THREAD

**Issue by sylouuu** [jenssegers/agent#52]
Hi,

What about this: http://stackoverflow.com/questions/6322112/check-if-php-page-is-accessed-from-an-ios-device ?

Bests

**Comment by jenssegers** [comment]
You could do `->isiOS()`.

**Comment by sylouuu** [comment]
Thank's for you quick answer. Where can I read all the available methods?

Bests

**Comment by jenssegers** [comment]
This library inherits all helper methods from http://mobiledetect.net

**Comment by igorsgm** [comment]
@jenssegers To be more specific, here is the list of all available methods:
http://demo.mobiledetect.net/
