### ISSUE TITLE
Tablet recognized as Mobile?

### ISSUE THREAD

**Issue by ilikourou** [jenssegers/agent#56]
Hello.

When I call `isMobile()` on an iPad it returns true. Should this be the case?

I am using `isMobile()` and `isTablet()` to find out if the user is visiting my site with a mobile (eg: iPhone), tablet (eg: iPad) or PC, so I can serve different content, based on each device.

Why isn't iPad recognized as Tablet?

Thank you,
Ilias

**Comment by dannyconnolly** [comment]
The Mobile Detect Library returns true for isMobile for both Mobile and Tablets. See first example example on the mobile detect [page](http://mobiledetect.net/).
