### ISSUE TITLE
Platform returns WebKit for Windows users on Windows 10

### ISSUE THREAD

**Issue by wouterds** [jenssegers/agent#61]
There's something wrong with `->platform()`, it returns `WebKit` for Windows 10 users. I will check this weekend in fixing this.

**Comment by jenssegers** [comment]
Can you provide the user agent string?

**Comment by tooblue** [comment]
I am having this issue as well. Here is the user agent string:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36`

**Comment by jenssegers** [comment]
@tooblue Added your UA to a test, and everything seems to be ok. 
https://github.com/jenssegers/agent/commit/c31032a041c2021343a279bce96e478468d59e80

**Comment by tokomeno** [comment]
Hi I have the same issue here is a dump of the agent class
`  #cache: []
  #userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
  #httpHeaders: array:9 [▼
    "HTTP_COOKIE" => "io=pwOgb0MCZIOjsWeaAAAF"
    "HTTP_ACCEPT_LANGUAGE" => "en-US,en;q=0.9,und;q=0.8,ka;q=0.7"
    "HTTP_ACCEPT_ENCODING" => "identity"
    "HTTP_ACCEPT" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
    "HTTP_USER_AGENT" => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36"
    "HTTP_UPGRADE_INSECURE_REQUESTS" => "1"
    "HTTP_CACHE_CONTROL" => "max-age=0"
    "HTTP_CONNECTION" => "close"
    "HTTP_HOST" => "localhost:8000"
  ]
  #cloudfrontHeaders: []
  #matchingRegex: "Chrome|\bCrMo\b|CriOS|Android.*Chrome/[.0-9]* (Mobile)?"
  #matchesArray: array:1 [▼
    0 => "Chrome"
  ]
  #detectionType: "mobile"`

And some other data from agent class:
`"device" => "WebKit"
  "platform" => "Linux"
  "browser" => "Chrome"
  "isDesktop" => true
  "isPhone" => false
  "isMobile" => false
  "isTablet" => false
`

**Comment by pouriabagheri** [comment]
facing the same issue
