### ISSUE TITLE
laravel 5.3 and failed to install because of the vendor publish issue

### ISSUE THREAD

**Issue by summermick** [jenssegers/agent#66]
I'm using laravel 5.3 and failed to install because 

> php artisan asset:publish vendor/package

  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "asset" namespace.         

Script php artisan asset:publish vendor/package handling the post-update-cmd event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

is there anyway I can install it on laravel 5.3?

**Comment by TonnyORG** [comment]
@summermick just type:
```bash
composer require jenssegers/agent
```

Then follow these steps:
https://github.com/TonnyORG/agent/blob/33043abec5a61d5ae6db2677c2c6457690801c71/README.md#laravel-optional
