### ISSUE TITLE
Compatible with laravel 5.0 and 5.3?

### ISSUE THREAD

**Issue by webcrazy** [jenssegers/agent#67]
Is it compatible with laravel 5.0 and laravel 5.3? I've tested with both and Facade is not working well. 

Thanks

**Comment by TonnyORG** [comment]
It it's with Laravel 5.3, I just tested it and it's working. I'm going to update the Docs to explain a little bit better how to setup it.

**Comment by karim-khan** [comment]
it is work 5.3 100% . i check this and i work my project and it is work

**Comment by webcrazy** [comment]
Yes no idea why it didn't work back there. Now try agin and it works fine.
