### ISSUE TITLE
Class Jenssegers\Agent\AgentServiceProvider not found on the server.

### ISSUE THREAD

**Issue by yash2code** [jenssegers/agent#75]
It worked perfectly on the localhost but on the server it is showing error.I've configured same on the server too.

Added the service provider in app/config/app.php:
'Jenssegers\Agent\AgentServiceProvider::class',

And added the Agent alias to app/config/app.php:
'Agent' => 'Jenssegers\Agent\Facades\Agent::class',

**Comment by ludo237** [comment]
Did you update the composer.json and the `/vendor` folder?

**Comment by Taytus** [comment]
Same error here. Works perfectly on local server, but live gives me this error.

**Comment by shnslmz** [comment]
Add this line top of AppServiceProvider.php:
use Agent;

like:
`namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Agent;`
