### ISSUE TITLE
Parse error on laravel 5.3

### ISSUE THREAD

**Issue by haco1123** [jenssegers/agent#78]
Hello, 
I'm using Laravel 5.3. 
If I use  php composer.phar require jenssegers/agent to install it, I get the error:
"Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /<url to page>/artisan on line 31
Script php artisan optimize handling the post-update-cmd event returned with error code 255

Installation failed, reverting ./composer.json to its original content."

How to fix it?
I use PHP 5.6.

**Comment by ludo237** [comment]
The error is on your side, I've just installed agent on a fresh Laravel 5.3 instance and it works great. Did you put the Service Provider inside `config/app.php` ?
