### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by cjke** [jenssegers/agent#79]
Minor issue, support for "share" has been dropped in 5.4. 

    public function register()
    {
        $this->app['agent'] = $this->app->share(function ($app)
        {
            return new Agent($app['request']->server->all());
        });
    }

Ref: https://laravel.com/docs/5.4/upgrade

I believe, in the case of Agent, it should be swapped out for `singleton`. 

Error currently:
```
> php artisan optimize


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Application::share()
```

**Comment by aemr3** [comment]
@cjke I got the same error. Master branch has this fix applied. But composer package is not updated yet. You can use dev-master as I did, for now.

**Comment by cjke** [comment]
Awesome - good tip - cheers!

**Comment by aemr3** [comment]
@jenssegers As people are trying to update Laravel right now I think it will be awesome if you look at this issue. Thanks.

**Comment by jenssegers** [comment]
Tagged new release. Should be ok now.

**Comment by aemr3** [comment]
Great! Thanks @jenssegers.
