### ISSUE TITLE
Problem with Application::share() in Laravel 5.4 version

### ISSUE THREAD

**Issue by fsasvari** [jenssegers/agent#80]
There is a problem with this package and Laravel 5.4 version.

I started composer update and following error occurs:
 - Call to undefined method Illuminate\Foundation\Application::share()
 - PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::share() in C:\xampp\htdocs\projects\name\vendor\jenssegers\agent\src\AgentServiceProvider.php on line 27

The solution is to use `$app->singleton()` instead.

**Comment by arcanedev-maroc** [comment]
See PR: #74

**Comment by SebastianS90** [comment]
This is fixed in `master` by #76, but unfortunately not yet released. You can update your `composer.json` file to use the `master` branch:
```javascript
"require": {
    "jenssegers/agent": "dev-master"
}
```

**Comment by jenssegers** [comment]
This was recently tagged.
