### ISSUE TITLE
Class 'Jenssegers\Agent\AgentServiceProvider' not found

### ISSUE THREAD

**Issue by LuizFernando1992** [jenssegers/agent#84]
I followed all the steps of the tutorial, but it is returning this error: Class 'Jenssegers\Agent\AgentServiceProvider' not found

**Comment by Rockindad** [comment]
I am having a very similar issue. Mine works fine in development (localhost) but getting "Class 'Jenssegers\Agent\Agent' not found"  when running in production.

**Comment by evilangelmd** [comment]
have you tried to clear compiled?
